Promis.NET.MCV/ViewModels/AccordionViewModel.cs
using Promis.NET.MCV.ViewModels.Interfaces;
using System.Collections.Generic;

namespace Promis.NET.MCV.ViewModels
{
    public class AccordionViewModel: BaseViewModel, IBaseViewModel
    {
        public string Title { get; set; } = string.Empty;
        public string Identifier { get; set; } = "accordion";
        public string Description { get; set; } = string.Empty;
        public string PathToRetrieveElements { get; set; } = string.Empty;
        public string MethodToInvoke { get; set; } = string.Empty;
        public Dictionary<string, string> Elements { get; set; } = new Dictionary<string, string>();

        public AccordionViewModel() { }
    }
}

Promis.NET.MCV/ViewModels/ModuleLayoutViewModel.cs
using System.Collections.Generic;

namespace Promis.NET.MCV.ViewModels
{
    public class ModuleLayoutViewModel
    {
        public string ModuleTitle { get; set; } = "";

        public string ModuleVersion { get; set; } = "";

        /// <summary>
        /// This should hold the key-value pairs for page description. The keys should be unique identifier for pages "of-this-format" and values should be "Titles for The Pages".
        /// The first entry should be 'home'.
        /// </summary>
        public Dictionary<string, string> PageDescriptorsContainer { get; set; } = new Dictionary<string, string>();

        /// <summary>
        /// This should hold the key-value pairs for page description, for the menu items that have dropdown selectors. The Key should be the equivalent of the key from the PageDescriptorsContainer dictionary (and the title displayed should be there), and the values should be the dropdown menu items. 
        /// </summary>
        public Dictionary<string, Dictionary<string, string>> PageDescriptorsForDropdowns { get; set; } = new Dictionary<string, Dictionary<string, string>>();

        /// <summary>
        /// Represents the id for the HTML element that will hold all the elements of the submodules (where submodule partial views will be loaded). Without the '#'.
        /// </summary>
        public string ContentContainerId { get; set; } = "module-container";

        public string WorkingPath { get; set; } = "mymodule";

        /// <summary>
        /// Define a list of stylesheets that should be available in all the module (usually there is just one).
        /// They should be strings, representing the path relative to 'assets/css' directory and starting with '/'.
        /// Example: '/pages/project-planning.css'.
        /// </summary>
        public List<string> StyleSheetsList { get; set; } = new List<string>();

        /// <summary>
        /// Define a list of Javascript elements that should be available in all the module (usually there is just one).
        /// They should be strings, representing the path relative to 'assets/js' directory and starting with '/'.
        /// Example: '/pages/project-planning.js'.
        /// </summary>
        public List<string> ScriptsList { get; set; } = new List<string>();
    }
}

Promis.NET.MCV/ViewModels/PdfViewerViewModel.cs
using Promis.NET.MCV.ViewModels.Interfaces;

namespace Promis.NET.MCV.ViewModels
{
    public class PdfViewerViewModel: BaseViewModel, IBaseViewModel
    {
        public string PageMode { get; set; } = "single";
        public string DocUrl { get; set; } = string.Empty;
        public string Title { get; set; } = "View PDF";
    }
}

Promis.NET.MCV/Controllers/ContentController.cs
using Promis.NET.Localization;
using Promis.NET.MCV.Extensions;
using Promis.NET.MCV.ViewModels;
using Promis.NET.Utilities.Exceptions;
using System;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Promis.NET.MCV.Controllers
{
    [Authorize]
    [RoutePrefix("content")]
    public class ContentController : Controller
    {
        private ControllerValidator _validator = new ControllerValidator();

        public ContentController()
        {
            // set current UI culture with the user language stored in claims
            if (Thread.CurrentPrincipal != null && Thread.CurrentPrincipal.Identity.IsAuthenticated && Thread.CurrentPrincipal.Identity.GetProjectId() != null)
            {
                var userLang = Thread.CurrentPrincipal.Identity.GetUserLanguage();
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(userLang);
            }
        }

        // GET: content
        [Route("download")]
        public FileResult Download(string type, string filePath)
        {
            if (string.IsNullOrWhiteSpace(type))
                throw new HttpException(400, LocalResources.FileTypeNotSpecified);
            if (string.IsNullOrWhiteSpace(filePath))
                throw new HttpException(400, LocalResources.FilePathNotSpecified);

            var errors = _validator.ValidateUserToBeInAnyReadModuleRole(User).GetErrors();
            if (errors.Count > 0)
                throw new UnauthorizedAccessException(errors[0]);

            string mimeType = "application/octet-stream";
            filePath = filePath.StartsWith("/") ? filePath.Substring(1) : filePath;
            var directory = "";

            if(type == "excel")
            {
                mimeType = "application/vnd.ms-excel";
                directory = "Excel Exports/";
            }

            if (type.StartsWith("image"))
            {
                mimeType = "image/*";
                directory = ParsePossibleSubdir("Images/", type);
            }

            if (type.StartsWith("pdf"))
            {
                mimeType = "application/pdf";
                directory = ParsePossibleSubdir("PDFs/", type);
            }

            var serverPath = System.Web.Hosting.HostingEnvironment.MapPath("~/App_Data/" + directory + filePath);
            if (!(new FileInfo(serverPath).Exists))
                throw new HttpException(404, LocalResources.FileNotFound);

            var stream = new FileStream(serverPath, FileMode.Open);
            return File(stream, mimeType, new FileInfo(serverPath).Name);
        }

        private string ParsePossibleSubdir(string directory, string type)
        {
            var typeSplit = type.Split('/');
            if (typeSplit.Length < 2)
                return directory;

            var subDir = typeSplit[1];
            if (string.IsNullOrWhiteSpace(subDir))
                return directory;
            
            subDir = subDir[0].ToString().ToUpper() + subDir.Substring(1);
            return directory + subDir + "/";
        }

        [HttpPost]
        [Route("upload")]
        public ActionResult Upload(string type)
        {
            var errors = _validator.ValidateUserToBeInAnyWriteModuleRole(User).GetErrors();
            if (errors.Count > 0)
                throw new UnauthorizedAccessException(errors[0]);

            var userName = User.Identity.Name;
            var projectDb = User.Identity.GetProjectDatabaseName();
            var baseFileName = projectDb + "-(" + userName + ")-" + Guid.NewGuid().ToString();
            var directory = "Uploads";

            if (Request.Files.Count == 0 || Request.Files[0].ContentLength == 0)
                return Json(new Envelope().AddError(LocalResources.NoFileToUpload).GetOnlyData());

            try
            {
                var file = Request.Files[0];
                var indexOfExtensionPoint = file.FileName.LastIndexOf(".");
                baseFileName += indexOfExtensionPoint > 0 ? "." + file.FileName.Substring(indexOfExtensionPoint + 1) : "";

                switch (type)
                {
                    case "excel":
                        directory = "Excel Imports";
                        break;
                    default:
                        break;
                }

                //create dir if it does not exist
                string dirPath = System.Web.Hosting.HostingEnvironment.MapPath("~/App_Data/" + directory + "/");
                if (!Directory.Exists(dirPath))
                    Directory.CreateDirectory(dirPath);

                string serverPath = dirPath + baseFileName;
                file.SaveAs(serverPath);
            }
            catch(Exception e)
            {
                return Json(new Envelope().SetErrorObject(PromisException.GetFromExistingException(e).ErrorDetailsUserLevel).GetOnlyData());
            }

            return Json(new Envelope().SetData(directory + "/" + baseFileName).GetOnlyData());
        }
        
        //GET: pdf?document=xxx&pageMode=xxy&title=xxz
        // document must be the path relative to the "PDFs" directory
        [Route("pdf")]
        public ActionResult DownloadAndViewPdf(string document, string pageMode, string title)
        {
            var errors = _validator.ValidateUserToBeInAnyReadModuleRole(User).GetErrors();
            if (errors.Count > 0)
                throw new UnauthorizedAccessException(errors[0]);

            var viewModel = new PdfViewerViewModel();
            var htmlFileName = "PdfViewer";

            viewModel.DocUrl = HttpUtility.UrlDecode(document);
            viewModel.PageMode = HttpUtility.UrlDecode(pageMode);
            viewModel.Title = HttpUtility.UrlDecode(title);

            return View(htmlFileName, viewModel);
        }

    }
}

Promis.NET.MCV/Views/Shared/PdfViewer.cshtml
@model Promis.NET.MCV.ViewModels.PdfViewerViewModel
@using Promis.NET.Localization

@{ var directDlLink = Url.Action("Download", "Content", new { type = "pdf", filePath = Model.DocUrl});
}
<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta content="width=device-width,initial-scale=1" name="viewport">
    <title>@LocalResources.Flip</title>
    <link type="text/css" href="~/assets/flip/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/assets/css/fonts/themify-icons.css" type="text/css">

    <!-- add js code -->
    <script src="~/assets/flip/js/jquery.js"></script>
    <script src="~/assets/flip/js/turn.js"></script>
    <script src="~/assets/flip/js/wait.js"></script>
    <script src="~/assets/flip/js/jquery.fullscreen.js"></script>

    <script src="~/assets/flip/js/jquery.address-1.6.min.js"></script>
    <script src="~/assets/flip/js/compatibility.js"></script>
    <script src="~/assets/flip/js/pdf.js"></script>
    <script src="~/assets/flip/js/pdf.worker.js"></script>
    <script src="~/assets/flip/js/onload.js"></script>

    <style>
        html, body {
            margin: 0;
            padding: 0;
            overflow: auto !important;
        }
    </style>
</head>
<body>
    <!-- begin flipbook  -->
    <div id="fb5-ajax" data-cat="Promis" data-template="true">
        <!-- BACKGROUND FLIPBOOK -->
        <div class="fb5-bcg-book" style="background-image: none; background-color: transparent!important"></div>
        <!-- BEGIN STRUCTURE HTML FLIPBOOK -->
        <div class="fb5" id="fb5">
            <!-- CONFIGURATION BOOK -->
            <section id="config">
                <ul>
                    <li key="page_width">918</li>               <!-- width for page -->
                    <li key="page_height">1298</li>             <!-- height for page -->
                    <li key="gotopage_width">25</li>            <!-- width for field input goto page -->
                    <li key="zoom_double_click">1</li>          <!-- value zoom after double click -->
                    <li key="zoom_step">0.06</li>				<!-- zoom step ( if click icon zoomIn or zoomOut -->
                    <li key="toolbar_visible">true</li>			<!-- enabled/disabled toolbar -->
                    <li key="tooltip_visible">true</li>			<!-- enabled/disabled tooltip for icon -->
                    <li key="deeplinking_enabled">false</li>   	<!-- enabled/disabled deeplinking -->
                    <li key="lazy_loading_pages">false</li>		<!-- enabled/disabled lazy loading for pages in flipbook -->
                    <li key="lazy_loading_thumbs">false</li>	<!-- enabled/disabled lazdy loading for thumbs -->
                    <li key="double_click_enabled">true</li> 	<!-- enabled/disabled double click mouse for flipbook -->
                    <li key="rtl">false</li>					<!-- enabled/disabled 'right to left' for eastern countries -->
                    <li key="pdf_url">@directDlLink</li>		                <!-- pathway to a pdf file ( the file will be read live ) -->
                    <li key="pdf_scale">2</li>					<!-- to live a pdf file (if you want to have a strong zoom - increase the value) -->
                    <li key="page_mode">@Model.PageMode</li>               <!-- value to 'single', 'double', or 'auto' -->
                </ul>
            </section>
            <!-- BEGIN PRELOADER -->
            <div class="fb5-preloader"></div>
            <!-- END PRELOADER -->
            <!-- BEGIN CONTAINER BOOK -->
            <div id="fb5-container-book">
                <!-- BEGIN deep linking -->
                <section id="fb5-deeplinking">
                    <ul>
                        <li data-address="page1" data-page="1"></li>
                        <li data-address="page2-page3" data-page="2"></li>
                        <li data-address="page2-page3" data-page="3"></li>
                        <li data-address="page4-page5" data-page="4"></li>
                        <li data-address="page4-page5" data-page="5"></li>
                        <li data-address="page6-page7" data-page="6"></li>
                        <li data-address="page6-page7" data-page="7"></li>
                        <li data-address="page8-page9" data-page="8"></li>
                        <li data-address="page8-page9" data-page="9"></li>
                        <li data-address="page10-page11" data-page="10"></li>
                        <li data-address="page10-page11" data-page="11"></li>
                        <li data-address="page12" data-page="12"></li>
                    </ul>
                </section>
                <!-- END deep linking -->
                <!-- BEGIN ABOUT -->
                <section id="fb5-about"></section>
                <!-- END ABOUT -->
                <!-- BEGIN LINKS -->
                <section id="links"></section>
                <!-- END LINKS -->
                <!-- BEGIN PAGES -->
                <div id="fb5-book">
                </div>
                <!-- END PAGES -->
            </div>
            <!-- END CONTAINER BOOK -->
            <!-- BEGIN FOOTER -->
            <div id="fb5-footer">
                <div class="fb5-bcg-tools" style="height:40px!important;"></div>
                <h2 id="fb5-logo" style="font-size: 20px!important;color: white!important; padding-left: 20px; line-height: 45px!important">@Model.Title</h2>
                <div class="fb5-menu" id="fb5-center">
                    <ul>
                        <li>
                            <a title="show cover page" class="fb5-home"><span class="ti-control-skip-backward"></span></a>
                        </li>
                        <li>
                            <a title="prev page" class="fb5-arrow-left"><span class="ti-control-backward"></span></a>
                        </li>
                        <li>
                            <a title="next page" class="fb5-arrow-right"><span class="ti-control-forward"></span></a>
                        </li>
                        <li>
                            <a title="zoom in" class="fb5-zoom-in"><span class="ti-zoom-in"></span></a>
                        </li>
                        <li>
                            <a title="zoom out" class="fb5-zoom-out"><span class="ti-zoom-out"></span></a>
                        </li>
                        <li>
                            <a title="one page" onClick="pagina('single')"><span class="ti-file"></span></a>
                        </li>

                        <li>
                            <a title="double pages" onClick="pagina('double')"><span class="ti-files"></span></a>
                        </li>
                        <li>
                            <a title="download pdf" class="fb5-download" href="@directDlLink" download="@directDlLink"><span class="ti-download"></span></a>
                        </li>
                        <li>
                            <a title="full/normal screen" class="fb5-fullscreen"><span class="ti-layout-media-center-alt"></span></a>
                        </li>
                    </ul>
                </div>

                <div class="fb5-menu" id="fb5-right">
                    <ul>
                        <!-- icon page manager -->
                        <li class="fb5-goto">
                            <label for="fb5-page-number" id="fb5-label-page-number"></label>
                            <input type="text" id="fb5-page-number" style="width: 25px;">
                            <span id="fb5-page-number-two"></span>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- END FOOTER -->
            <!-- BEGIN ALL PAGES -->
            <div id="fb5-all-pages" class="fb5-overlay">
                <section class="fb5-container-pages">
                    <div id="fb5-menu-holder">
                        <ul id="fb5-slider">
                            <!-- thumb 1 -->
                            <li class="1">
                                <img alt="" data-src="pages/1_.jpg">
                            </li>
                            <!-- thumb 2 -->
                            <li class="2">
                                <img alt="" data-src="pages/2_.jpg">
                            </li>
                            <!-- thumb 3 -->
                            <li class="3">
                                <!-- img -->
                                <img alt="" data-src="pages/3_.jpg">
                            </li>
                            <!-- thumb 4 -->
                            <li class="4">
                                <!-- img -->
                                <img alt="" data-src="pages/4_.jpg">
                            </li>
                            <!-- thumb 5 -->
                            <li class="5">
                                <!-- img -->
                                <img alt="" data-src="pages/5_.jpg">
                            </li>
                            <!-- thumb 6 and 7 -->
                            <li class="6">
                                <!-- img -->
                                <img alt="" data-src="pages/6_7_.jpg">
                            </li>
                            <!-- thumb 8 and 9 -->
                            <li class="8">
                                <!-- img -->
                                <img alt="" data-src="pages/8_9_.jpg">
                            </li>
                            <!-- thumb 10 -->
                            <li class="10">
                                <!-- img -->
                                <img alt="" data-src="pages/10_.jpg">
                            </li>
                            <!-- thumb 11 -->
                            <li class="11">
                                <!-- img -->
                                <img alt="" data-src="pages/11_.jpg">
                            </li>
                            <!-- thumb 12 -->
                            <li class="12">
                                <!-- img -->
                                <img alt="" data-src="pages/12_.jpg">
                            </li>
                        </ul>
                    </div>
                </section>
            </div>
            <!-- END ALL PAGES -->
            <!-- BEGIN CLOSE LIGHTBOX  -->
            <div id="fb5-close-lightbox">
                <i class="fa fa-times pull-right"></i>
            </div>
            <!-- END CLOSE LIGHTBOX -->
        </div>
        <!-- END STRUCTURE HTML FLIPBOOK -->
    </div>
    <!-- end flipbook -->

    <script>
        function pagina(type) {
            document.location = "content/pdf?document=" + encodeURIComponent("@Model.DocUrl")
                + "&pageMode=" + encodeURIComponent("@Model.PageMode")
                + "&title=" + encodeURIComponent("@Model.Title");
        }
    </script>
</body>
</html>

Promis.NET.MCV/Views/Shared/_Accordion.cshtml
@using Promis.NET.MCV.ViewModels
@{ Html.RenderPartial("_Error", new Envelope(ViewBag.Envelope, true)); }

@model Promis.NET.MCV.ViewModels.AccordionViewModel

<div class="card accordion-card">
    <div class="card-header">
        <span class="text-white accordion-title">@Model.Title</span>
        <h5 class="card-subtitle mb-2 text-muted">@Model.Description</h5>
    </div>

    <div id="@Model.Identifier" role="tablist" aria-multiselectable="true" class="accordion">
        @foreach (var kvp in Model.Elements)
        {
            var containerId = Model.Identifier + "-" + kvp.Key;
            var headerId = "h" + containerId;
            <div class="card">
                <div id="@headerId" class="card-header accordion-element-title" role="tab">
                    <p class="mb-0 pull-left">
                        <a class="in text-white accordion-trigger" data-code="@kvp.Key" data-toggle="collapse" data-parent="#@Model.Identifier" href="#@containerId" aria-expanded="true" aria-controls="@containerId">
                            <i class="fa fa-angle-down fa-lg mr-2"></i>@kvp.Value
                        </a>
                    </p>
                </div>
                <div id="@containerId" class="collapsed in collapse" role="tabpanel" aria-labelledby="@headerId" aria-expanded="true">
                    <div class="card-block text-white accordion-element-container">
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>
    $("#@Html.Raw(Model.Identifier + " .accordion-trigger")").click(function () {
        var contentId = $(this).attr("href");
        var innerContentId = contentId + " .accordion-element-container";
        var isDisplayed = $(contentId).hasClass("show");
        if (isDisplayed) {
            //$(contentId).removeClass("show"); done auto
            $(innerContentId).html("");
            return;
        }

        // call server to get data
        var url = GLOBAL_DATA.APP_ROOT + "/" + "@Model.PathToRetrieveElements" + "?code=" + $(this).attr("data-code");
        callServer(url, {
            elementsToAddLoading: [contentId],
            removeLoaderIfFail: true,
            successFunc: function (viewHtml) {
                $(innerContentId).html(viewHtml);
                $(contentId).addClass("show");
                @{ 
                    if(!string.IsNullOrWhiteSpace(Model.MethodToInvoke))
                    {
                        Html.Raw(Model.MethodToInvoke + "()");
                    }
                }
            }
        });
    });
</script>

Promis.NET.MCV/Views/Shared/_Error.cshtml
@using Promis.NET.Utilities.Extensions
@model Promis.NET.MCV.ViewModels.Envelope

@{ 
    var isValid = Model != null && Model.errors != null;
    var isArray = isValid && (Model.errors.GetType().IsArray || Model.errors.GetType() == typeof(List<string>)) && Model.errors.Count > 0;
    var isPromisError = isValid && Model.errors.GetType() == typeof(Promis.NET.Utilities.Exceptions.ErrorDetails);
}
@if (isArray || isPromisError)
{
    <script>
        validateEnvelopeError(@ObjectExtensions.ToHtmlJson(@Model));
    </script>
}

Promis.NET.MCV/Views/Shared/_Layout.cshtml
@using Promis.NET.Utilities.Extensions
@using Promis.NET.MCV.Extensions
@using Promis.NET.Localization

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <!-- Specify to the browser we are responsive-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Icon -->
    <link rel="icon" href="~/favicon.ico">

    <!-- Title -->
    <title>@ViewBag.Title | Promis</title>

    <!-- Font Awesome Icons CSS -->
    <link rel="stylesheet" href="~/assets/css/libraries/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/libraries/themify-icons.css" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/libraries/bootstrap.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/libraries/roboto.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/libraries/spinkit.css" type="text/css">

    <!-- Addons -->
    <link rel="stylesheet" href="~/assets/css/addons.css" type="text/css" />

    <script src="~/assets/js/global.js"></script>

    <!-- Themes -->
    <link id="theme" rel="stylesheet" href="@Html.Raw("/assets/css/themes/" + Request.GetOwinContext().Request.User.Identity.GetUserTheme() + ".css")" type="text/css">

    <!-- CHILD STYLES START -->
    @RenderSection("styles", required: false)
    <!-- CHILD STYLES END -->
</head>

<body class="menuclose menuclose-right">

    <!-- CONTENT START -->
    @RenderBody()

    <!--Modal-->
    <div class="modal dark_bg fade" id="modal-container" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header row" id="modal-head">
                    <h6 class="pull-left modal-title" id="modal-label">&nbsp;</h6>
                    <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <div id="modal-footer-versioning" class="col-md-4 left left-align"><small id="modal-version">F004.M001.V1.0.0.0</small></div>
                    <div id="modal-footer-content"></div>
                </div>
            </div>
        </div>
    </div>
    <!--End of Modal-->
    <!-- CONTENT END -->
    <!-- SCRIPTS START -->
    <!-- jQuery first (header), then Tether, then Bootstrap JS. -->
    <script src="~/assets/js/libraries/jquery-3.2.1.min.js"></script>
    <script src="~/assets/js/libraries/tether.min.js"></script>

    <script src="~/assets/js/libraries/bootstrap.min.js"></script>
    <script src="~/assets/js/libraries/notify.js"></script>
    <script src="~/assets/js/libraries/lodash.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    @if (Request.Browser.Browser == "IE" && Request.Browser.MajorVersion < 9)
    {
        <script src="~/assets/js/libraries/html5shiv.min.js"></script>
        <script src="~/assets/js/libraries/respond.min.js"></script>
    }

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="~/assets/js/libraries/ie10-viewport-bug-workaround.js"></script>

    <!-- Utils -->
    <script>
        @{var propData = "";}
           var GLOBAL_TRANSLATIONS_FOR_LAYOUT = {
                @propData.GetPropertyName(() => LocalResources.ChartsNotAvailableToChangeTheme): @LocalResources.ChartsNotAvailableToChangeTheme.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.PageUnderConstruction): @LocalResources.PageUnderConstruction.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.Modal): @LocalResources.Modal.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.Creating): @LocalResources.Creating.ToHtmlJson(),

                @propData.GetPropertyName(() => LocalResources.AddRecord): @LocalResources.AddRecord.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.CannotUpdateThisRow): @LocalResources.CannotUpdateThisRow.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.UpdateRecord): @LocalResources.UpdateRecord.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.DeleteRecord): @LocalResources.DeleteRecord.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.DeleteSelectedRecordbrbrareYouSure): @LocalResources.DeleteSelectedRecordbrbrareYouSure.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.Confirm): @LocalResources.Confirm.ToHtmlJson(),
                @propData.GetPropertyName(() => LocalResources.ThereIsNoDataForThisSelection): @LocalResources.ThereIsNoDataForThisSelection.ToHtmlJson()
            };

    </script>
    <script src="~/assets/js/helpers/loader.js"></script>
    <script src="~/assets/js/addons.js"></script>

    <!-- CHILD SCRIPTS START -->
    @RenderSection("scripts", required: false)
    <!-- CHILD SCRIPTS END -->
    <!-- SCRIPTS END -->
</body>
</html>